using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Art.Chemistry;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;
using Content.Shared.FixedPoint;
using Robust.Client.Graphics;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Client.GameObjects;
using System.Threading.Tasks;
using Robust.Client.ResourceManagement;

namespace Content.Client.Chemistry.UI
{
    /// <summary>
    /// Client-side UI used to control a ChemMaster.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class ChemMasterWindow : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;
        private readonly SpriteSystem _sprite;

        // Events
        public event Action<BaseButton.ButtonEventArgs, ReagentButton, int, bool>? OnReagentButtonPressed;
        public event Action? OnToggleValveButtonPressed; // Starlight-edit: Plumbing valve
        public event Action<int>? OnAmountButtonPressed;
        public event Action<int>? OnSortMethodChanged;
        public event Action<int>? OnTransferAmountChanged;
        public event Action<List<int>>? OnUpdateAmounts;
        public event Action<ReagentId, bool, bool>? OnTransferAllPressed;
        public event Action<ReagentId>? OnAnalyzeReagentPressed; // SS14-Art: Chemical Analysis
        public event Action<ReagentId, int>? OnSelectReagentAmount;
        public event Action<ReagentId, int>? OnRemoveReagentAmount;
        public event Action<int>? OnToggleBottleFillPressed;
        public event Action<int>? OnBottleSlotEjectPressed;
        public event Action<int>? OnRowEjectPressed;
        public event Action<int>? OnPillContainerSlotSelected;
        public event Action<int>? OnPillCanisterSelected;
        public event Action<int>? OnPillCanisterEjected;
        public event Action<ReagentId, int>? OnTransferReagentFromBottle;

        // UI State
        public bool IsOutputTab => Tabs.CurrentTab == 1;
        private bool _deleteMode = false;

        public readonly Button[] PillContainerStorageButtons;
        public readonly Button[] BottleStorageButtons;
        public readonly Button[] BottleEjectButtons;
        public readonly Button[] RowEjectButtons;
        public readonly Button[] PillTypeButtons;

        private const string TransferringAmountColor = "#ffffff";
        private const int MaxAmountButtons = 20;
        private const string PillsRsiPath = "/Textures/Objects/Specific/Chemistry/pills.rsi";

        private List<int> _amounts = new();
        private ReagentSortMethod _currentSortMethod = ReagentSortMethod.Alphabetical;
        private ChemMasterBoundUserInterfaceState? _lastState;
        private int _transferAmount = 50;
        private int _selectedBottleIndex = -1;
        private bool _labelLineEditFocused = false;
        private Dictionary<ReagentId, float>? _lastSelectedReagentAmounts = null;

        public ChemMasterWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _sprite = _entityManager.System<SpriteSystem>();

            AmountLabel.HorizontalAlignment = HAlignment.Center;
            AmountLineEdit.OnTextEntered += SetAmount;

            DeleteAsFrequentButton.OnPressed += HandleDeleteModeToggled;
            SaveAsFrequentButton.OnPressed += HandleSaveAsFrequentPressed;

            // Pill type selection buttons
            var resourcePath = new ResPath(PillsRsiPath);
            var pillTypeGroup = new ButtonGroup();
            PillTypeButtons = new Button[20];
            for (uint i = 0; i < PillTypeButtons.Length; i++)
            {
                string styleNano = StyleClass.ButtonOpenBoth;
                uint modulo = i % 10;
                if (i > 0 && modulo == 0)
                    styleNano = StyleClass.ButtonOpenRight;
                else if (i > 0 && modulo == 9)
                    styleNano = StyleClass.ButtonOpenLeft;
                else if (i == 0)
                    styleNano = StyleClass.ButtonOpenRight;

                PillTypeButtons[i] = new Button
                {
                    Access = AccessLevel.Public,
                    StyleClasses = { styleNano },
                    MaxSize = new Vector2(42, 28),
                    Group = pillTypeGroup
                };

                var specifier = new SpriteSpecifier.Rsi(resourcePath, "pill" + (i + 1));
                PillTypeButtons[i].AddChild(new TextureRect
                {
                    Texture = _sprite.Frame0(specifier),
                    TextureScale = new Vector2(1.75f, 1.75f),
                    Stretch = TextureRect.StretchMode.KeepCentered,
                });
                Grid.AddChild(PillTypeButtons[i]);
            }

            PillDosage.InitDefaultButtons();
            PillNumber.InitDefaultButtons();
            BottleDosage.InitDefaultButtons();
            BottleNumber.InitDefaultButtons();

            // Starlight-start: Patch buttons
            PatchDosage.InitDefaultButtons();
            PatchNumber.InitDefaultButtons();
            // Starlight-end

            PillNumber.IsValid = x => x >= 0;
            PillDosage.IsValid = x => x >= 0;
            BottleNumber.IsValid = x => x >= 0;
            BottleDosage.IsValid = x => x >= 0;

            PillDosage.ValueChanged += _ => UpdateLabelFromState();
            PillNumber.ValueChanged += _ => UpdateLabelFromState();
            BottleDosage.ValueChanged += _ => UpdateLabelFromState();
            BottleNumber.ValueChanged += _ => UpdateLabelFromState();
            BottleNumber.LineEditControl.OnTextChanged += _ => UpdateLabelFromState();
            BottleDosage.LineEditControl.OnTextChanged += _ => UpdateLabelFromState();
            PillNumber.LineEditControl.OnTextChanged += _ => UpdateLabelFromState();
            PillDosage.LineEditControl.OnTextChanged += _ => UpdateLabelFromState();

            // Bottle storage grid: 5 rows × 4 cols + row eject button per row
            BottleStorageButtons = new Button[20];
            BottleEjectButtons = new Button[20];
            RowEjectButtons = new Button[5];
            for (int row = 0; row < 5; row++)
            {
                for (int col = 0; col < 4; col++)
                {
                    int i = row * 4 + col;
                    var cell = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true };

                    var mainButton = new Button
                    {
                        HorizontalExpand = true,
                        VerticalExpand = true,
                        StyleClasses = { StyleNano.ButtonSquare },
                        ToggleMode = true
                    };

                    var ejectButton = new Button
                    {
                        VerticalExpand = true,
                        StyleClasses = { StyleNano.ButtonOpenLeft }
                    };
                    ejectButton.MinSize = new Vector2(20, 0);
                    ejectButton.MaxSize = new Vector2(20, float.MaxValue);
                    ejectButton.AddChild(new Label
                    {
                        Text = Loc.GetString("chem-master-window-eject-container-button"),
                        VerticalAlignment = VAlignment.Center,
                        HorizontalAlignment = HAlignment.Center,
                        Margin = new Thickness(-7, -4, 0, 0)
                    });

                    int buttonIndex = i;
                    mainButton.OnPressed += _ => OnToggleBottleFillPressed?.Invoke(buttonIndex);
                    ejectButton.OnPressed += _ => OnBottleSlotEjectPressed?.Invoke(buttonIndex);

                    BottleStorageButtons[i] = mainButton;
                    BottleEjectButtons[i] = ejectButton;

                    cell.AddChild(mainButton);
                    cell.AddChild(ejectButton);
                    BottleStorageGrid.AddChild(cell);
                }

                var rowEjectButton = new Button
                {
                    Text = Loc.GetString("chem-master-window-eject-row-button"),
                    StyleClasses = { StyleNano.ButtonCaution },
                    VerticalExpand = true
                };
                int rowIndex = row;
                rowEjectButton.OnPressed += _ => OnRowEjectPressed?.Invoke(rowIndex);
                RowEjectButtons[row] = rowEjectButton;
                BottleStorageGrid.AddChild(rowEjectButton);
            }

            // Pill container grid: 3 rows × (choose button + 10 slots + eject button) = 12 columns
            PillContainerStorageButtons = new Button[30];

            for (int containerRow = 0; containerRow < 3; containerRow++)
            {
                var chooseButton = new Button
                {
                    Text = Loc.GetString("chem-master-window-pill-canister-choose-button"),
                    StyleClasses = { StyleNano.StyleClassButtonColorGreen },
                    MinSize = new Vector2(105, 30),
                    MaxSize = new Vector2(105, 30),
                    ToggleMode = true,
                    HorizontalExpand = true
                };
                int chooseIndex = containerRow;
                chooseButton.OnPressed += _ => OnPillCanisterSelected?.Invoke(chooseIndex);
                PillContainerStorageGrid.AddChild(chooseButton);

                for (int pillSlot = 0; pillSlot < 10; pillSlot++)
                {
                    int i = containerRow * 10 + pillSlot;
                    var mainButton = new Button
                    {
                        StyleClasses = { StyleNano.ButtonSquare },
                        ToggleMode = true,
                        Margin = new Thickness(2),
                        MinSize = new Vector2(28, 28),
                        MaxSize = new Vector2(28, 28),
                        Disabled = true
                    };
                    int slotIndex = i;
                    mainButton.OnPressed += _ => OnPillContainerSlotSelected?.Invoke(slotIndex);
                    PillContainerStorageButtons[i] = mainButton;
                    PillContainerStorageGrid.AddChild(mainButton);
                }

                var ejectButton = new Button
                {
                    Text = Loc.GetString("chem-master-window-eject-row-button"),
                    StyleClasses = { StyleNano.ButtonCaution },
                    MinSize = new Vector2(105, 30),
                    MaxSize = new Vector2(105, 30),
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Stretch
                };
                int ejectIndex = containerRow;
                ejectButton.OnPressed += _ => OnPillCanisterEjected?.Invoke(ejectIndex);
                PillContainerStorageGrid.AddChild(ejectButton);
            }

            LabelLineEdit.IsValid = s => s.Length <= SharedChemMaster.LabelMaxLength;
            LabelLineEdit.OnFocusEnter += _ => _labelLineEditFocused = true;
            LabelLineEdit.OnFocusExit += _ => _labelLineEditFocused = false;

            Tabs.SetTabTitle(0, Loc.GetString("chem-master-window-buffer-tab"));
            Tabs.SetTabTitle(1, Loc.GetString("chem-master-window-output-tab"));
            Tabs.OnTabChanged += _ => UpdateLabelFromState();

            SortMethod.AddItem(Loc.GetString("chem-master-window-sort-method-amount-text"), (int)ReagentSortMethod.Amount);
            SortMethod.AddItem(Loc.GetString("chem-master-window-sort-method-alphabetical-text"), (int)ReagentSortMethod.Alphabetical);
            SortMethod.AddItem(Loc.GetString("chem-master-window-sort-method-time-text"), (int)ReagentSortMethod.Time);
            SortMethod.MinSize = new Vector2(300, 29);
            SortMethod.HorizontalAlignment = HAlignment.Stretch;
            SortMethod.OnItemSelected += HandleChildPressed;

            BufferTransferButton.OnPressed += HandleDiscardTransferPress;
            BufferDiscardButton.OnPressed += HandleDiscardTransferPress;

            // Starlight-start: Plumbing valve
            ValveButton.OnPressed += _ => OnToggleValveButtonPressed?.Invoke();
            // Starlight-end

            CreateAmountButtons();
        }

        private ReagentButton MakeReagentButton(string text, ReagentId id, bool isBuffer)
        {
            var btn = new ReagentButton(text, id, isBuffer);
            btn.OnPressed += args => OnReagentButtonPressed?.Invoke(args, btn, _transferAmount, IsOutputTab);
            return btn;
        }

        private void CreateAmountButtons()
        {
            AmountButtons.DisposeAllChildren();
            int buttonsToShow = Math.Min(_amounts.Count, MaxAmountButtons);
            for (int i = 0; i < buttonsToShow; i++)
            {
                var styleClass = StyleNano.ButtonOpenBoth;
                var amount = _amounts[i];
                var columns = AmountButtons.Columns;
                if (i == 0 || i % columns == 0)
                    styleClass = StyleNano.ButtonOpenRight;
                if ((i + 1) % columns == 0)
                    styleClass = StyleNano.ButtonOpenLeft;

                var button = new Button
                {
                    Text = amount.ToString(),
                    MinSize = new Vector2(10, 10),
                    StyleClasses = { styleClass },
                    HorizontalExpand = true
                };
                button.OnPressed += _ => HandleAmountButtonPressed(amount);
                AmountButtons.AddChild(button);
            }
        }

        private void HandleSaveAsFrequentPressed(BaseButton.ButtonEventArgs args)
        {
            if (!int.TryParse(AmountLineEdit.Text, out var amount)) { ShowWarningMessage(Loc.GetString("chem-master-window-amount-empty")); return; }
            if (amount > 1000) { ShowWarningMessage(Loc.GetString("chem-master-window-amount-too-much")); return; }
            if (amount <= 0) { ShowWarningMessage(Loc.GetString("chem-master-window-amount-invalid")); return; }
            if (_amounts.Any(a => amount == a)) { ShowWarningMessage(Loc.GetString("chem-master-window-amount-duplicate")); return; }
            if (_amounts.Count >= MaxAmountButtons) { ShowWarningMessage(Loc.GetString("chem-master-window-amount-limit-reached")); return; }

            _amounts.Add(amount);
            _amounts.Sort();
            CreateAmountButtons();
            OnUpdateAmounts?.Invoke(_amounts);
            AmountLineEdit.SetText(string.Empty);
        }

        private async void ShowWarningMessage(string message)
        {
            WarningLabel.Text = message;
            WarningLabel.Visible = true;
            await Task.Delay(3000);
            WarningLabel.Text = string.Empty;
            WarningLabel.Visible = false;
        }

        private bool TryGetSelectedAmount(ReagentId reagent, ChemMasterBoundUserInterfaceState? state, out float selectedAmount)
        {
            selectedAmount = 0;
            state ??= _lastState;
            if (state?.SelectedReagentAmounts == null || state.SelectedReagentAmounts.Count == 0)
                return false;

            if (state.SelectedReagentAmounts.TryGetValue(reagent, out selectedAmount))
                return selectedAmount > 0;

            foreach (var kvp in state.SelectedReagentAmounts)
            {
                if (kvp.Key.Equals(reagent)) { selectedAmount = kvp.Value; return selectedAmount > 0; }
            }
            foreach (var kvp in state.SelectedReagentAmounts)
            {
                if (kvp.Key.Prototype == reagent.Prototype) { selectedAmount = kvp.Value; return selectedAmount > 0; }
            }
            return false;
        }

        private float GetTotalSelectedReagentAmount()
        {
            if (_lastState?.SelectedReagentAmounts == null) return 0;
            float total = 0;
            foreach (var amount in _lastState.SelectedReagentAmounts.Values)
                total += amount;
            return total;
        }

        private void UpdateDosageAndNumberFromSelection()
        {
            var totalAmount = GetTotalSelectedReagentAmount();
            if (totalAmount == 0 || _lastState == null)
            {
                PillNumber.Value = 0; PillDosage.Value = 0;
                BottleNumber.Value = 0; BottleDosage.Value = 0;
                return;
            }

            var maxPillDosage = (int)_lastState.PillDosageLimit;
            var maxBottleDosage = (int)_lastState.BottleDosageLimit;
            var maxPills = (int)_lastState.MaxPills;
            var maxBottles = (int)_lastState.MaxBottles;

            if (totalAmount < maxPillDosage) { PillNumber.Value = 1; PillDosage.Value = (int)totalAmount; }
            else { PillDosage.Value = maxPillDosage; PillNumber.Value = (int)Math.Min(totalAmount / maxPillDosage, maxPills); }

            if (totalAmount < maxBottleDosage) { BottleNumber.Value = 1; BottleDosage.Value = (int)totalAmount; }
            else { BottleDosage.Value = maxBottleDosage; BottleNumber.Value = (int)Math.Min(totalAmount / maxBottleDosage, maxBottles); }
        }

        private void HandleDeleteModeToggled(BaseButton.ButtonEventArgs args)
        {
            _deleteMode = DeleteAsFrequentButton.Pressed;
        }

        private void HandleAmountButtonPressed(int amount)
        {
            if (_deleteMode)
            {
                _amounts.Remove(amount);
                CreateAmountButtons();
                OnUpdateAmounts?.Invoke(_amounts);
            }
            else
            {
                OnAmountButtonPressed?.Invoke(amount);
                SetAmountText(amount.ToString());
            }
        }

        private void HandleDiscardTransferPress(BaseButton.ButtonEventArgs args)
        {
            var bufferButtons = BufferInfo.Children.Where(c => c is Button).Cast<Button>();
            foreach (var button in bufferButtons)
            {
                var text = BufferTransferButton.Pressed ? "transfer" : "discard";
                button.Text = Loc.GetString($"chem-master-window-{text}-button");
            }
        }

        private void UpdatePillCanisterButtonStates()
        {
            if (_lastState == null) return;
            var pillGrid = FindControl<GridContainer>("PillContainerStorageGrid");
            if (pillGrid == null) return;

            for (int i = 0; i < 3; i++)
            {
                var chooseButton = pillGrid.Children.ElementAt(i * 12) as Button;
                if (chooseButton == null) continue;
                var isSelected = _lastState.SelectedPillCanisterForCreation == i;
                chooseButton.Pressed = isSelected;
                chooseButton.Modulate = isSelected ? Color.LimeGreen : Color.White;
                if (chooseButton.Label != null)
                    chooseButton.Label.ModulateSelfOverride = Color.White;
            }
        }

        private void HandleSortMethodChange(int newSortMethod)
        {
            if (newSortMethod == (int)_currentSortMethod) return;
            _currentSortMethod = (ReagentSortMethod)newSortMethod;
            SortMethod.SelectId(newSortMethod);
            if (_lastState != null) UpdateState(_lastState);
        }

        private void HandleChildPressed(OptionButton.ItemSelectedEventArgs args)
        {
            HandleSortMethodChange(args.Id);
            OnSortMethodChanged?.Invoke(args.Id);
        }

        private bool ValidateAmount(string newText, bool invokeEvent = true)
        {
            if (string.IsNullOrWhiteSpace(newText) || !int.TryParse(newText, out int amount) || amount <= 0)
            {
                AmountLineEdit.SetText(string.Empty);
                return false;
            }
            _transferAmount = amount;
            if (invokeEvent) OnTransferAmountChanged?.Invoke(amount);
            return true;
        }

        private void SetAmount(LineEdit.LineEditEventArgs args) => SetAmountText(args.Text);

        private void SetAmountText(string newText, bool invokeEvent = true)
        {
            if (newText == _transferAmount.ToString() || !ValidateAmount(newText, invokeEvent)) return;
            AmountLabel.Text = Loc.GetString("chem-master-window-transferring-label", ("quantity", newText), ("color", TransferringAmountColor));
            AmountLineEdit.SetText(string.Empty);
        }

        private ReagentButton? CreateReagentTransferButton(ReagentId reagent, bool isBuffer, bool addReagentButtons)
        {
            if (!addReagentButtons) return null;
            var isTransfer = BufferTransferButton.Pressed;
            var text = isTransfer ? "transfer" : "discard";
            return MakeReagentButton(Loc.GetString($"chem-master-window-{text}-button"), reagent, isBuffer);
        }

        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ChemMasterBoundUserInterfaceState) state;
            _lastState = castState;

            HandleSortMethodChange(castState.SortMethod);
            UpdatePanelInfo(castState);

            PillDosage.IsValid = x => x >= 0 && x <= (int)castState.PillDosageLimit;
            BottleDosage.IsValid = x => x >= 0 && x <= (int)castState.BottleDosageLimit;
            PillNumber.IsValid = x => x >= 0 && x <= (int)castState.MaxPills;
            BottleNumber.IsValid = x => x >= 0 && x <= (int)castState.MaxBottles;

            // Starlight-start: patch dosage validation
            PatchDosage.IsValid = x => x >= 0 && x <= (int)castState.PatchDosageLimit;
            PatchNumber.IsValid = x => x >= 0;
            // Starlight-end

            bool selectedReagentsChanged = _lastSelectedReagentAmounts == null ||
                !_lastSelectedReagentAmounts.SequenceEqual(castState.SelectedReagentAmounts ?? new Dictionary<ReagentId, float>());

            if (selectedReagentsChanged)
                _lastSelectedReagentAmounts = castState.SelectedReagentAmounts != null
                    ? new Dictionary<ReagentId, float>(castState.SelectedReagentAmounts)
                    : null;

            UpdateDosageAndNumberFromSelection();

            if (!_labelLineEditFocused && (castState.UpdateLabel || selectedReagentsChanged))
                LabelLine = GenerateLabel(castState);

            SetAmountText(castState.TransferringAmount.ToString(), false);

            if (!_amounts.SequenceEqual(castState.Amounts))
            {
                _amounts = castState.Amounts;
                _amounts.Sort();
                CreateAmountButtons();
            }

            InputEjectButton.Disabled = castState.ContainerInfo is null;

            var totalSelectedAmount = GetTotalSelectedReagentAmount();
            var pillTotalNeeded = PillNumber.Value * PillDosage.Value;
            CreatePillButton.Disabled = !(castState.BufferReagents.Count > 0 && PillNumber.Value > 0 && PillDosage.Value > 0 && pillTotalNeeded <= totalSelectedAmount);

            var bottleTotalNeeded = BottleNumber.Value * BottleDosage.Value;
            CreateBottleButton.Disabled = !(castState.BufferReagents.Count > 0 && BottleNumber.Value > 0 && BottleDosage.Value > 0 && bottleTotalNeeded <= totalSelectedAmount);

            // Starlight-start: patch button
            var patchTotalNeeded = PatchNumber.Value * PatchDosage.Value;
            CreatePatchButton.Disabled = !(castState.BufferReagents.Count > 0 && PatchNumber.Value > 0 && PatchDosage.Value > 0 && patchTotalNeeded <= totalSelectedAmount);
            // Starlight-end

            // Starlight-start: valve button
            ValveButton.Text = Loc.GetString(castState.ValveOpen ? "chem-master-window-valve-open" : "chem-master-window-valve-closed");
            // Starlight-end

            UpdateBottleStorage(castState);
            UpdatePillContainerStorage(castState);
            UpdatePillContainerContents(castState);
            UpdatePillCanisterButtonStates();
        }

        private Color GetMixedReagentColor(List<ReagentQuantity> reagents)
        {
            if (reagents == null || !reagents.Any()) return Color.White;
            Color mixColor = default;
            var runningTotal = FixedPoint2.Zero;
            bool first = true;
            foreach (var reagent in reagents)
            {
                runningTotal += reagent.Quantity;
                if (!_prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto)) continue;
                if (first) { first = false; mixColor = proto.SubstanceColor; continue; }
                mixColor = Color.InterpolateBetween(mixColor, proto.SubstanceColor, reagent.Quantity.Float() / runningTotal.Float());
            }
            return mixColor;
        }

        private void UpdateBottleStorage(ChemMasterBoundUserInterfaceState state)
        {
            for (int i = 0; i < BottleStorageButtons.Length; i++)
            {
                var button = BottleStorageButtons[i];
                var info = state.StoredBottles[i];
                if (info != null)
                {
                    button.Text = $"{info.CurrentVolume}/{info.MaxVolume}";
                    button.Modulate = (info.Reagents != null && info.Reagents.Any()) ? GetMixedReagentColor(info.Reagents) : Color.White;
                    button.ToggleMode = true;
                    button.Pressed = state.SelectedBottleForFill == i;
                }
                else
                {
                    button.Text = Loc.GetString("chem-master-window-storage-empty");
                    button.Modulate = Color.Gray;
                    button.Pressed = false;
                    button.ToggleMode = false;
                }
                if (BottleEjectButtons != null && BottleEjectButtons.Length > i && BottleEjectButtons[i] != null)
                    BottleEjectButtons[i].Disabled = info == null;
            }
            _selectedBottleIndex = state.SelectedBottleForFill;
            UpdateBottleContents(state);
        }

        private void UpdateBottleContents(ChemMasterBoundUserInterfaceState state)
        {
            BottleContentsInfo.Children.Clear();
            if (_selectedBottleIndex < 0 || _selectedBottleIndex >= state.StoredBottles.Count || state.StoredBottles[_selectedBottleIndex] == null)
            {
                BottleContentsInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-no-bottle-selected-text") });
                return;
            }
            var bottleInfo = state.StoredBottles[_selectedBottleIndex];
            if (bottleInfo == null) { BottleContentsInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-no-bottle-selected-text") }); return; }

            var headerHBox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            headerHBox.AddChild(new Label
            {
                Text = Loc.GetString("chem-master-window-bottle-label", ("current", bottleInfo.CurrentVolume), ("max", bottleInfo.MaxVolume)),
                StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }
            });
            BottleContentsInfo.AddChild(headerHBox);

            if (bottleInfo.Reagents == null || !bottleInfo.Reagents.Any())
            {
                BottleContentsInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-storage-empty") });
                return;
            }

            int rowCount = 0;
            foreach (var reagent in bottleInfo.Reagents)
            {
                _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                if (name.Length > 17) name = AbbreviateReagentName(name);
                BottleContentsInfo.AddChild(BuildSimpleReagentRow(proto?.SubstanceColor ?? default, rowCount++, name, reagent.Quantity, reagent.Reagent));
            }
        }

        private Control BuildSimpleReagentRow(Color reagentColor, int rowCount, string name, FixedPoint2 quantity, ReagentId reagentId, bool addTransferButton = true)
        {
            var rowColor1 = Color.FromHex("#1B1B1E");
            var rowColor2 = Color.FromHex("#202025");
            var currentRowColor = (rowCount % 2 == 1) ? rowColor1 : rowColor2;
            if (reagentColor == default) reagentColor = currentRowColor;

            var rowContainer = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            rowContainer.AddChild(new BoxContainer
            {
                MinWidth = 130,
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Children =
                {
                    new Label { Text = $"{name}: ", HorizontalAlignment = HAlignment.Left },
                    new Label { Text = $"{quantity}u", StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }, HorizontalAlignment = HAlignment.Left }
                }
            });
            rowContainer.AddChild(new PanelContainer
            {
                Name = "colorPanel",
                VerticalExpand = true,
                MinWidth = 4,
                PanelOverride = new StyleBoxFlat { BackgroundColor = reagentColor },
                Margin = new Thickness(0, 1)
            });

            if (addTransferButton)
            {
                var transferButton = new Button { Text = "↑", MinWidth = 30, MaxWidth = 30, StyleClasses = { StyleNano.ButtonOpenLeft } };
                if (transferButton.Label != null)
                {
                    var resCache = IoCManager.Resolve<IResourceCache>();
                    transferButton.Label.FontOverride = resCache.NotoStack(variation: "Bold", size: 12);
                }
                transferButton.OnPressed += _ => OnTransferReagentFromBottle?.Invoke(reagentId, _transferAmount);
                rowContainer.AddChild(transferButton);
            }

            return new PanelContainer { PanelOverride = new StyleBoxFlat(currentRowColor), Children = { rowContainer } };
        }

        private void UpdatePillContainerStorage(ChemMasterBoundUserInterfaceState state)
        {
            for (int i = 0; i < PillContainerStorageButtons.Length; i++)
            {
                var button = PillContainerStorageButtons[i];
                var containerIndex = i / 10;
                var slotIndex = i % 10;

                if (containerIndex < state.StoredPillContainers.Count)
                {
                    var containerInfo = state.StoredPillContainers[containerIndex];
                    if (containerInfo != null)
                    {
                        var maxPills = (int)containerInfo.MaxVolume;
                        var pillEntities = state.PillContainers[containerIndex];

                        if (slotIndex < pillEntities.Count && pillEntities[slotIndex])
                        {
                            button.Text = "";
                            uint pillType = (containerIndex < state.PillTypes.Count && slotIndex < state.PillTypes[containerIndex].Count)
                                ? state.PillTypes[containerIndex][slotIndex]
                                : 0;
                            var spriteState = (pillType > 0 && pillType <= 20) ? $"pill{pillType + 1}" : "pill1";
                            var specifier = new SpriteSpecifier.Rsi(new ResPath(PillsRsiPath), spriteState);
                            button.Children.Clear();
                            button.AddChild(new TextureRect
                            {
                                Texture = _sprite.Frame0(specifier),
                                TextureScale = new Vector2(1.5f, 1.5f),
                                Stretch = TextureRect.StretchMode.KeepCentered,
                                HorizontalAlignment = HAlignment.Center,
                                VerticalAlignment = VAlignment.Center
                            });
                            button.Modulate = Color.White;
                        }
                        else if (slotIndex < maxPills)
                        {
                            button.Children.Clear();
                            button.Modulate = Color.LightGray;
                        }
                        else
                        {
                            button.Children.Clear();
                            button.Modulate = Color.Gray;
                        }
                        button.Disabled = false;
                        button.Pressed = state.SelectedPillContainerSlot == i;
                    }
                    else
                    {
                        button.Children.Clear();
                        button.Modulate = Color.LightGray;
                        button.Disabled = true;
                        button.Pressed = false;
                    }
                }
                else
                {
                    button.Children.Clear();
                    button.Modulate = Color.LightGray;
                    button.Disabled = true;
                }
            }
        }

        private void UpdatePillContainerContents(ChemMasterBoundUserInterfaceState state)
        {
            PillContainerContentsInfo.Children.Clear();
            if (state.SelectedPillContainerSlot < 0 || state.SelectedPillContainerSlot >= PillContainerStorageButtons.Length)
            {
                PillContainerContentsInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-no-pill-selected-text") });
                return;
            }
            var pillInfo = state.SelectedPillContainerInfo;
            if (pillInfo == null) { PillContainerContentsInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-no-pill-selected-text") }); return; }

            var headerHBox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            headerHBox.AddChild(new Label
            {
                Text = Loc.GetString("chem-master-window-pill-label", ("current", pillInfo.CurrentVolume), ("max", pillInfo.MaxVolume)),
                StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }
            });
            PillContainerContentsInfo.AddChild(headerHBox);

            if (pillInfo.Reagents == null || !pillInfo.Reagents.Any())
            {
                PillContainerContentsInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-storage-empty") });
                return;
            }

            int rowCount = 0;
            foreach (var reagent in pillInfo.Reagents)
            {
                _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                if (name.Length > 17) name = AbbreviateReagentName(name);
                PillContainerContentsInfo.AddChild(BuildSimpleReagentRow(proto?.SubstanceColor ?? default, rowCount++, name, reagent.Quantity, reagent.Reagent, addTransferButton: false));
            }
        }

        private string GenerateLabel(ChemMasterBoundUserInterfaceState state)
        {
            return GenerateLabelWithDosage(state, (uint)PillDosage.Value);
        }

        public string GeneratePillLabel()
        {
            if (_lastState == null) return LabelLine;
            return GenerateLabelWithDosage(_lastState, (uint)PillDosage.Value);
        }

        // Starlight-start
        public string GeneratePatchLabel()
        {
            if (_lastState == null) return LabelLine;
            return GenerateLabelWithDosage(_lastState, (uint)PatchDosage.Value);
        }
        // Starlight-end

        public string GenerateBottleLabel()
        {
            if (_lastState == null) return LabelLine;
            return GenerateLabelWithDosage(_lastState, (uint)BottleDosage.Value);
        }

        private string GenerateLabelWithDosage(ChemMasterBoundUserInterfaceState state, uint dosage)
        {
            if (state.SelectedReagentAmounts == null || state.SelectedReagentAmounts.Count == 0) return "";
            if (dosage == 0) return "";

            FixedPoint2 totalSelectedAmount = FixedPoint2.Zero;
            foreach (var amount in state.SelectedReagentAmounts.Values)
                totalSelectedAmount += FixedPoint2.New(amount);
            if (totalSelectedAmount <= 0) return "";

            var scale = FixedPoint2.New(dosage) / totalSelectedAmount;
            var reagentAmounts = new Dictionary<ReagentId, FixedPoint2>();
            var totalForWithdrawal = FixedPoint2.Zero;
            var reagentList = state.SelectedReagentAmounts.ToList();

            for (int i = 0; i < reagentList.Count - 1; i++)
            {
                var (reagentId, selectedAmount) = reagentList[i];
                var scaledAmount = FixedPoint2.New(selectedAmount) * scale;
                reagentAmounts[reagentId] = scaledAmount;
                totalForWithdrawal += scaledAmount;
            }
            if (reagentList.Count > 0)
            {
                var lastReagent = reagentList[reagentList.Count - 1].Key;
                reagentAmounts[lastReagent] = FixedPoint2.New(dosage) - totalForWithdrawal;
            }

            var parts = new List<string>();
            foreach (var (reagentId, amount) in reagentAmounts)
            {
                if (_prototypeManager.TryIndex<ReagentPrototype>(reagentId.Prototype, out var reagentProto))
                {
                    var reagentName = reagentProto.LocalizedName;
                    if (reagentName.Length > 17) reagentName = AbbreviateReagentName(reagentName);
                    parts.Add($"{reagentName}:{amount:F0}u");
                }
            }
            return string.Join("/", parts);
        }

        private void UpdateLabelFromState()
        {
            if (_lastState != null && !_labelLineEditFocused)
            {
                var newLabel = GenerateLabel(_lastState);
                if (!string.IsNullOrEmpty(newLabel))
                    LabelLine = newLabel;
            }
        }

        private void UpdatePanelInfo(ChemMasterBoundUserInterfaceState state)
        {
            BufferTransferButton.Pressed = state.Mode == ChemMasterMode.Transfer;
            BufferDiscardButton.Pressed = state.Mode == ChemMasterMode.Discard;
            BuildContainerUI(ContainerInfoContainer, state.ContainerInfo, true);
            BuildBufferInfo(state);
        }

        private void BuildBufferInfo(ChemMasterBoundUserInterfaceState state)
        {
            BufferInfo.Children.Clear();

            if (!state.BufferReagents.Any())
            {
                BufferInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });
                return;
            }

            var bufferHBox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            BufferInfo.AddChild(bufferHBox);
            bufferHBox.AddChild(new Label { Text = $"{Loc.GetString("chem-master-window-buffer-label")} " });
            bufferHBox.AddChild(new Label { Text = $"{state.BufferCurrentVolume}u", StyleClasses = { StyleClass.LabelWeak } });

            IReadOnlyList<ReagentQuantity> bufferReagents = state.BufferReagents;
            if (_currentSortMethod == ReagentSortMethod.Amount)
                bufferReagents = bufferReagents.OrderByDescending(x => x.Quantity).ToList();
            else if (_currentSortMethod == ReagentSortMethod.Alphabetical)
                bufferReagents = bufferReagents.OrderBy(x =>
                {
                    _prototypeManager.TryIndex(x.Reagent.Prototype, out ReagentPrototype? proto);
                    return proto?.LocalizedName ?? string.Empty;
                }).ToList();

            var reagents = _currentSortMethod == ReagentSortMethod.Time ? state.BufferReagents : bufferReagents;
            int rowCount = 0;
            foreach (var (reagentId, quantity) in reagents)
            {
                _prototypeManager.TryIndex(reagentId.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                if (name.Length > 17) name = AbbreviateReagentName(name);
                BufferInfo.Children.Add(BuildReagentRow(proto?.SubstanceColor ?? default, rowCount++, name, reagentId, quantity, true, true, state));
            }
        }

        private string AbbreviateReagentName(string fullName)
        {
            if (string.IsNullOrWhiteSpace(fullName)) return fullName;
            var words = fullName.Split(new[] { ' ', '\t', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
            if (words.Length == 0) return fullName;
            if (words.Length == 1)
            {
                var word = words[0];
                return word.Length > 5 ? word.Substring(0, word.Length - 5) : word;
            }
            var abbreviated = new List<string>();
            for (int i = 0; i < words.Length - 1; i++)
                abbreviated.Add(words[i].Length <= 3 ? words[i] : words[i].Substring(0, 3) + ".");
            abbreviated.Add(words[words.Length - 1]);
            return string.Join(" ", abbreviated);
        }

        private void BuildContainerUI(Control control, ContainerInfo? info, bool addReagentButtons)
        {
            control.Children.Clear();
            if (info is null)
            {
                control.Children.Add(new Label { Text = Loc.GetString("chem-master-window-no-container-loaded-text") });
                return;
            }

            control.Children.Add(new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    new Label { Text = $"{info.DisplayName}: " },
                    new Label { Text = $"{info.CurrentVolume}/{info.MaxVolume}", StyleClasses = { StyleClass.LabelWeak } }
                }
            });

            int rowCount = 0;
            if (info.Entities != null)
            {
                foreach (var (id, quantity) in info.Entities.Select(x => (x.Id, x.Quantity)))
                    control.Children.Add(BuildReagentRow(default, rowCount++, id, default, quantity, false, false));
            }
            if (info.Reagents != null)
            {
                foreach (var reagent in info.Reagents)
                {
                    _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto);
                    var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                    if (name.Length > 17) name = AbbreviateReagentName(name);
                    control.Children.Add(BuildReagentRow(proto?.SubstanceColor ?? default, rowCount++, name, reagent.Reagent, reagent.Quantity, false, addReagentButtons));
                }
            }
        }

        private Control BuildReagentRow(Color reagentColor, int rowCount, string name, ReagentId reagent, FixedPoint2 quantity, bool isBuffer, bool addReagentButtons, ChemMasterBoundUserInterfaceState? state = null)
        {
            Button? selectButton = null;
            Button? removeButton = null;
            Button? analyzeButton = null; // SS14-Art
            Control? buttonsSpacing = null;

            if (isBuffer && reagent != default)
            {
                selectButton = new Button
                {
                    Text = "✓",
                    StyleClasses = { StyleNano.StyleClassButtonColorGreen, StyleNano.ButtonSquare },
                    MinSize = new Vector2(30, 0)
                };
                selectButton.OnPressed += _ =>
                {
                    var amountToUse = _transferAmount;
                    if (!string.IsNullOrWhiteSpace(AmountLineEdit.Text) && int.TryParse(AmountLineEdit.Text, out var parsed) && parsed > 0)
                    {
                        SetAmountText(AmountLineEdit.Text, true);
                        amountToUse = _transferAmount;
                    }
                    OnSelectReagentAmount?.Invoke(reagent, amountToUse);
                };

                removeButton = new Button
                {
                    Text = "✗",
                    StyleClasses = { StyleNano.StyleClassButtonColorRed, StyleNano.ButtonSquare },
                    MinSize = new Vector2(30, 0)
                };
                removeButton.OnPressed += _ =>
                {
                    var amountToUse = _transferAmount;
                    if (!string.IsNullOrWhiteSpace(AmountLineEdit.Text) && int.TryParse(AmountLineEdit.Text, out var parsed) && parsed > 0)
                    {
                        SetAmountText(AmountLineEdit.Text, true);
                        amountToUse = _transferAmount;
                    }
                    OnRemoveReagentAmount?.Invoke(reagent, amountToUse);
                };

                buttonsSpacing = new Control { MinSize = new Vector2(15, 0) };

                // SS14-Art start: Chemical Analysis button
                analyzeButton = new Button
                {
                    Text = "⚗",
                    StyleClasses = { StyleNano.ButtonSquare },
                    MinSize = new Vector2(30, 0),
                    ToolTip = Loc.GetString("chem-analysis-window-title")
                };
                analyzeButton.OnPressed += _ => OnAnalyzeReagentPressed?.Invoke(reagent);
                // SS14-Art end
            }

            var rowColor1 = Color.FromHex("#1B1B1E");
            var rowColor2 = Color.FromHex("#202025");
            var currentRowColor = (rowCount % 2 == 1) ? rowColor1 : rowColor2;
            if (reagentColor == default || !addReagentButtons) reagentColor = currentRowColor;

            var reagentButtonConstructor = CreateReagentTransferButton(reagent, isBuffer, addReagentButtons);

            var rowContainer = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

            var statsContainer = new BoxContainer
            {
                MinWidth = 130,
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    new Label { Text = $"{name}: ", HorizontalAlignment = HAlignment.Left },
                    new Label { Text = $"{quantity}u", StyleClasses = { StyleNano.StyleClassLabelSecondaryColor }, HorizontalAlignment = HAlignment.Left }
                }
            };

            if (selectButton != null) rowContainer.AddChild(selectButton);
            if (removeButton != null) rowContainer.AddChild(removeButton);
            if (analyzeButton != null) rowContainer.AddChild(analyzeButton); // SS14-Art
            if (buttonsSpacing != null) rowContainer.AddChild(buttonsSpacing);
            rowContainer.AddChild(statsContainer);
            rowContainer.AddChild(new Control { HorizontalExpand = true });

            var colorPanel = new PanelContainer
            {
                Name = "colorPanel",
                VerticalExpand = true,
                MinWidth = 4,
                PanelOverride = new StyleBoxFlat { BackgroundColor = reagentColor },
                Margin = new Thickness(0, 1)
            };

            if (reagentButtonConstructor != null)
            {
                if (isBuffer && reagent != default)
                {
                    var leftContainer = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Vertical,
                        VerticalExpand = true,
                        MinWidth = 120,
                        HorizontalExpand = true
                    };
                    var selectedLabel = new Label
                    {
                        StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                        HorizontalAlignment = HAlignment.Left,
                        VerticalAlignment = VAlignment.Center,
                        HorizontalExpand = true
                    };
                    var currentState = state ?? _lastState;
                    if (TryGetSelectedAmount(reagent, currentState, out var selectedAmount))
                    {
                        selectedLabel.Text = Loc.GetString("chem-master-window-reagent-selected",
                            ("amount", Math.Round(selectedAmount, 2)));
                    }
                    leftContainer.AddChild(selectedLabel);
                    rowContainer.AddChild(leftContainer);
                    rowContainer.AddChild(colorPanel);
                }
                else
                {
                    rowContainer.AddChild(colorPanel);
                }

                rowContainer.AddChild(reagentButtonConstructor);
                var transferAllButton = new Button
                {
                    Text = Loc.GetString("chem-master-window-buffer-all-amount"),
                    StyleClasses = { StyleNano.ButtonOpenLeft }
                };
                transferAllButton.OnPressed += _ => OnTransferAllPressed?.Invoke(reagent, isBuffer, IsOutputTab);
                rowContainer.AddChild(transferAllButton);
            }
            else
            {
                rowContainer.AddChild(colorPanel);
            }

            return new PanelContainer { PanelOverride = new StyleBoxFlat(currentRowColor), Children = { rowContainer } };
        }

        public string LabelLine
        {
            get => LabelLineEdit.Text;
            set => LabelLineEdit.Text = value;
        }

        public ReagentId? SelectedReagentId => string.IsNullOrEmpty(_lastState?.SelectedReagent?.Prototype) ? null : _lastState.SelectedReagent;

        // Starlight: Patch SpinBox accessors — генерируются автоматически из XAML через GenerateTypedNameReferences
        // public SpinBox PatchDosage { get; }
        // public SpinBox PatchNumber { get; }
        // public Button CreatePatchButton { get; }
        // public Button ValveButton { get; }
    }

    public sealed class ReagentButton : Button
    {
        public bool IsBuffer = true;
        public ReagentId Id { get; set; }

        public ReagentButton(string text, ReagentId id, bool isBuffer)
        {
            AddStyleClass(StyleNano.ButtonSquare);
            Text = text;
            Id = id;
            IsBuffer = isBuffer;
        }
    }

    public enum ReagentSortMethod
    {
        Time,
        Alphabetical,
        Amount
    }
}
