using Content.Client.UserInterface.Controls;
using Content.Shared._Art.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Art.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class ChemAnalysisPopup : FancyWindow
{
    public event Action<ReagentId>? OnPrintPressed;

    private readonly ReagentId _reagentId;

    public ChemAnalysisPopup(ChemReagentAnalysisPopupMessage message)
    {
        RobustXamlLoader.Load(this);

        _reagentId = message.ReagentId;
        Title = Loc.GetString("chem-analysis-window-title");
        TitleLabel.Text = Loc.GetString("chem-analysis-window-title");
        NameValue.Text = message.Title;
        DescriptionValue.SetMessage(message.Description);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke(_reagentId);
    }
}
