using Content.Client.SubFloor;
using Content.Client._Art.Administration; // ss14-art-edit
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Sandbox.Windows;

[GenerateTypedNameReferences]
public sealed partial class SandboxWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = null!;

    public SandboxWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void Opened()
    {
        base.Opened();
        // Make sure state is up to date.
        ToggleSubfloorButton.Pressed = _entManager.System<SubFloorHideSystem>().ShowAll;
        // ss14-art-edit start
        var doorMaster = _entManager.System<DoorMasterSystem>();
        ToggleDoorsButton.Pressed = doorMaster.Enabled;
        // ss14-art-edit end
    }
}
